import type { Metadata } from 'next';
import { HtmlFormatter } from '@/components/tools/HtmlFormatter';
import { ToolInfoSection } from '@/components/ToolInfoSection';
import { RelatedTools } from '@/components/RelatedTools';

export const metadata: Metadata = {
  title: 'HTML Beautifier – Format and Indent HTML Code',
  description: 'Format, indent, and beautify messy HTML code. Free online tool to make your web code readable and well-structured.',
  alternates: { canonical: 'https://tools2do.com/tools/html-formatter/html-beautifier' },
};

const jsonLd = {"@context":"https://schema.org","@type":"WebApplication","name":"HTML Beautifier Online","description":"Format, indent, and beautify messy HTML code. Free online tool to make your web code readable and well-structured.","applicationCategory":"DeveloperApplication","operatingSystem":"Web Browser","offers":{"@type":"Offer","price":"0","priceCurrency":"USD"},"url":"https://tools2do.com/tools/html-formatter/html-beautifier"};

export default function Page(): React.ReactElement {
  return (
    <>
      <script id="tool-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
      <div className="mx-auto max-w-5xl px-4 pt-10 md:px-6">
        <h1 className="text-[length:var(--text-h1)] font-extrabold text-[var(--text-primary)]">HTML Beautifier Online</h1>
        <p className="mt-3 max-w-2xl text-[var(--text-secondary)]">Turn unreadable, minified HTML into a beautifully indented document. Easy to use tool for web developers and designers.</p>
      </div>
      <HtmlFormatter />
      <ToolInfoSection
        howToSteps={[{ step: 'Paste HTML', description: 'Input your messy or minified HTML string.' }, { step: 'Beautify', description: 'Click format to automatically add correct indentation and line breaks.' }, { step: 'Copy Result', description: 'Copy the clean code to your editor.' }]}
        useCases={['Making scraped HTML content from websites readable.', 'Formatting inline HTML strings found inside JavaScript templates.', 'Cleaning up code generated by WYSIWYG editors.']}
        privacyNote="All processing is executed locally using your browser. Your data is never sent to a server."
      />
      <RelatedTools
        tools={[{ href: '/tools/css-formatter', name: 'CSS Formatter', description: 'Beautify CSS stylesheets.' }]}
      />
    </>
  );
}