export type ToolCategory = 'developer' | 'pakistan-utility' | 'text' | 'image' | 'converter' | 'calculator';

export type Tool = {
  id: string;
  name: string;
  slug: string;
  category: ToolCategory;
  icon: string;
  description: string;
  shortDescription: string;
  isPakistani: boolean;
  tileSize: 'large' | 'medium' | 'small';
  keywords: string[];
  isNew?: boolean;
  isFeatured?: boolean;
};

export const TOOLS_REGISTRY: Tool[] = [
  // === FEATURED / LARGE ===
  { id:'json-formatter',      name:'JSON Formatter & Validator', slug:'/tools/json-formatter',       category:'developer',         icon:'Braces',      description:'Format, validate, minify, and inspect JSON entirely in your browser.',              shortDescription:'JSON Formatter',     isPakistani:false, tileSize:'large',  keywords:['json','formatter','validator','minify','developer'], isFeatured:true },
  { id:'image-compressor',    name:'Image Compressor',           slug:'/tools/image-compressor',     category:'image',             icon:'ImageDown',   description:'Compress JPEG, PNG, and WebP files client-side without uploading to a server.',    shortDescription:'Image Compress',     isPakistani:false, tileSize:'large',  keywords:['image','compressor','jpeg','png','webp'],           isFeatured:true },
  { id:'word-counter',        name:'Word Counter',               slug:'/tools/word-counter',         category:'text',              icon:'WholeWord',   description:'Count words, characters, sentences, paragraphs and reading time instantly.',        shortDescription:'Word Counter',       isPakistani:false, tileSize:'large',  keywords:['word','counter','text','characters','sentences'],   isFeatured:true },
  // === IMAGE TOOLS ===
  { id:'image-converter',     name:'Image Converter',            slug:'/tools/image-converter',      category:'image',             icon:'ImageDown',   description:'Convert images to JPG, PNG or WebP. Batch convert, resize, adjust quality and rename files.',  shortDescription:'Image Converter',    isPakistani:false, tileSize:'large',  keywords:['image','converter','jpg','png','webp','convert'],   isFeatured:true, isNew:true },
  { id:'image-resizer',       name:'Image Resizer',              slug:'/tools/image-resizer',        category:'image',             icon:'Crop',        description:'Resize images with custom dimensions or quick presets for Instagram, Facebook, and Twitter.',   shortDescription:'Image Resizer',      isPakistani:false, tileSize:'medium', keywords:['image','resizer','resize','crop','dimensions']      },
  { id:'image-to-pdf',        name:'Image to PDF',               slug:'/tools/image-to-pdf',         category:'image',             icon:'FileDown',    description:'Convert multiple images to a single PDF. Reorder pages, set a custom file name and download.',   shortDescription:'Image to PDF',       isPakistani:false, tileSize:'medium', keywords:['image','pdf','convert','pages']                     },
  { id:'pdf-merge-split',     name:'PDF Merge & Split',          slug:'/tools/pdf-merge-split',      category:'developer',         icon:'FilePlus',    description:'Merge multiple PDFs into one or split a PDF by extracting specific pages with pdf-lib.',         shortDescription:'PDF Tools',          isPakistani:false, tileSize:'medium', keywords:['pdf','merge','split','pages','combine']             },
  // === MEDIUM ===
  { id:'character-counter',   name:'Character Counter',          slug:'/tools/character-counter',    category:'text',              icon:'AlignLeft',   description:'Count characters with platform limit bars for Twitter, Instagram, SMS and more.',   shortDescription:'Char Counter',       isPakistani:false, tileSize:'medium', keywords:['character','counter','twitter','instagram','sms']  },
  { id:'password-generator',  name:'Password Generator',         slug:'/tools/password-generator',   category:'developer',         icon:'KeyRound',    description:'Generate strong random passwords with configurable length and character sets.',    shortDescription:'Password Gen',       isPakistani:false, tileSize:'medium', keywords:['password','generator','secure','random','crypto']  },
  { id:'case-converter',      name:'Case Converter',             slug:'/tools/case-converter',       category:'text',              icon:'Type',        description:'Convert text to UPPERCASE, lowercase, Title Case, sentence case, or slug-format.', shortDescription:'Case Converter',     isPakistani:false, tileSize:'medium', keywords:['case','converter','uppercase','lowercase','title'] },
  { id:'regex-tester',        name:'Regex Tester',               slug:'/tools/regex-tester',         category:'developer',         icon:'Regex',       description:'Test regular expressions against sample text with match highlighting.',            shortDescription:'Regex Tester',       isPakistani:false, tileSize:'medium', keywords:['regex','regexp','tester','match']                  },
  { id:'css-formatter',       name:'CSS Formatter',              slug:'/tools/css-formatter',        category:'developer',         icon:'FileCode2',   description:'Format or minify CSS stylesheets in your browser.',                              shortDescription:'CSS Formatter',      isPakistani:false, tileSize:'medium', keywords:['css','formatter','minifier','stylesheet']          },
  { id:'csv-to-json',         name:'CSV to JSON Converter',      slug:'/tools/csv-to-json',          category:'converter',         icon:'Table2',      description:'Convert CSV data to formatted JSON instantly in your browser.',                   shortDescription:'CSV → JSON',         isPakistani:false, tileSize:'medium', keywords:['csv','json','converter','table']                   },
  { id:'find-and-replace',    name:'Find and Replace',           slug:'/tools/find-and-replace',     category:'text',              icon:'Replace',     description:'Find and replace text with plain text or regex patterns.',                       shortDescription:'Find & Replace',     isPakistani:false, tileSize:'medium', keywords:['find','replace','text','regex']                    },
  { id:'percentage-calculator',name:'Percentage Calculator',     slug:'/tools/percentage-calculator',category:'calculator',        icon:'Calculator',  description:'Calculate percentages, increases and decreases instantly.',                       shortDescription:'% Calculator',       isPakistani:false, tileSize:'medium', keywords:['percentage','calculator','math','increase']        },
  { id:'age-calculator',      name:'Age Calculator',             slug:'/tools/age-calculator',       category:'calculator',        icon:'Calendar',    description:'Calculate exact age in years, months and days from a date of birth.',             shortDescription:'Age Calculator',     isPakistani:false, tileSize:'medium', keywords:['age','calculator','birthday','date']               },
  { id:'unit-converter',      name:'Unit Converter',             slug:'/tools/unit-converter',       category:'converter',         icon:'ArrowLeftRight',description:'Convert length, weight, temperature and volume units.',                        shortDescription:'Unit Converter',     isPakistani:false, tileSize:'medium', keywords:['unit','converter','length','weight','temperature'] },
  // === SMALL ===
  { id:'base64',              name:'Base64 Encoder Decoder',     slug:'/tools/base64',               category:'converter',         icon:'Binary',      description:'Encode and decode Base64 strings instantly in your browser.',                    shortDescription:'Base64',             isPakistani:false, tileSize:'small',  keywords:['base64','encode','decode']                         },
  { id:'url-encoder',         name:'URL Encoder Decoder',        slug:'/tools/url-encoder',          category:'converter',         icon:'Link',        description:'Encode or decode URL components and query strings safely.',                      shortDescription:'URL Encode',         isPakistani:false, tileSize:'small',  keywords:['url','encode','decode']                            },
  { id:'slug-generator',      name:'Slug Generator',             slug:'/tools/slug-generator',       category:'developer',         icon:'Hash',        description:'Generate clean URL slugs from any title or phrase.',                            shortDescription:'Slug Gen',           isPakistani:false, tileSize:'small',  keywords:['slug','url','seo','generator']                     },
  { id:'timestamp-converter', name:'Timestamp Converter',        slug:'/tools/timestamp-converter',  category:'converter',         icon:'Clock3',      description:'Convert Unix timestamps to human-readable dates and back.',                      shortDescription:'Timestamp',          isPakistani:false, tileSize:'small',  keywords:['timestamp','unix','date','epoch']                  },
  { id:'javascript-formatter',name:'JavaScript Formatter',       slug:'/tools/javascript-formatter', category:'developer',         icon:'Braces',      description:'Format or minify JavaScript code in your browser.',                             shortDescription:'JS Formatter',       isPakistani:false, tileSize:'small',  keywords:['javascript','js','formatter','minifier']           },
  { id:'html-formatter',      name:'HTML Formatter',             slug:'/tools/html-formatter',       category:'developer',         icon:'FileCode2',   description:'Format or minify HTML markup in your browser.',                                 shortDescription:'HTML Formatter',     isPakistani:false, tileSize:'small',  keywords:['html','formatter','minifier','markup']             },
  { id:'uuid-generator',      name:'UUID Generator',             slug:'/tools/uuid-generator',       category:'developer',         icon:'Fingerprint', description:'Generate v4 UUIDs locally for apps, databases, and tests.',                     shortDescription:'UUID Gen',           isPakistani:false, tileSize:'small',  keywords:['uuid','guid','random','id']                        },
  { id:'remove-extra-spaces', name:'Remove Extra Spaces',        slug:'/tools/remove-extra-spaces',  category:'text',              icon:'Eraser',      description:'Clean text by removing duplicate spaces, tabs and blank lines.',                 shortDescription:'Clean Spaces',       isPakistani:false, tileSize:'small',  keywords:['spaces','clean','whitespace','remove']             },
  { id:'text-repeater',       name:'Text Repeater',              slug:'/tools/text-repeater',        category:'text',              icon:'Repeat',      description:'Repeat any word, sentence or paragraph multiple times.',                         shortDescription:'Text Repeater',      isPakistani:false, tileSize:'small',  keywords:['repeat','text','duplicate']                        },
  { id:'lorem-ipsum-generator',name:'Lorem Ipsum Generator',     slug:'/tools/lorem-ipsum-generator',category:'text',              icon:'AlignJustify',description:'Generate clean placeholder text for designs, websites and layouts.',             shortDescription:'Lorem Ipsum',        isPakistani:false, tileSize:'small',  keywords:['lorem','ipsum','placeholder','text']               },
  { id:'qr-code-generator',   name:'QR Code Generator',          slug:'/tools/qr-code-generator',    category:'developer',         icon:'QrCode',      description:'Generate QR codes for URLs, text and contacts.',                                shortDescription:'QR Code',            isPakistani:false, tileSize:'small',  keywords:['qr','code','generator','barcode']                  },
  { id:'color-converter',     name:'Color Converter',            slug:'/tools/color-converter',      category:'converter',         icon:'Pipette',     description:'Convert HEX colors to RGB and RGB to HEX with a live color swatch.',            shortDescription:'HEX ↔ RGB',          isPakistani:false, tileSize:'small',  keywords:['color','hex','rgb','converter']                    },

  // === PAKISTAN UTILITIES ===
  { id:'lesco-bill',    name:'LESCO Bill Checker',               slug:'/pk/check-lesco-bill',                    category:'pakistan-utility', icon:'ReceiptText', description:'Validate LESCO reference number and get step-by-step bill check guidance.',  shortDescription:'LESCO Bill',    isPakistani:true, tileSize:'large',  keywords:['lesco','lahore','bill','reference number'],          isFeatured:true },
  { id:'ke-bill',       name:'K-Electric Bill Checker',          slug:'/pk/check-ke-electric-bill',              category:'pakistan-utility', icon:'Zap',         description:'Validate K-Electric account reference for Karachi electricity bill check.',   shortDescription:'KE Bill',       isPakistani:true, tileSize:'large',  keywords:['ke','k electric','karachi','bill']                   },
  { id:'mepco-bill',    name:'MEPCO Bill Checker',               slug:'/pk/check-mepco-bill',                    category:'pakistan-utility', icon:'ReceiptText', description:'Validate MEPCO reference numbers for Multan region users.',                    shortDescription:'MEPCO Bill',    isPakistani:true, tileSize:'medium', keywords:['mepco','multan','bill']                              },
  { id:'iesco-bill',    name:'IESCO Bill Checker',               slug:'/pk/check-iesco-bill',                    category:'pakistan-utility', icon:'ReceiptText', description:'Validate IESCO reference numbers for Islamabad and Rawalpindi customers.',     shortDescription:'IESCO Bill',    isPakistani:true, tileSize:'medium', keywords:['iesco','islamabad','rawalpindi','bill']              },
  { id:'gepco-bill',    name:'GEPCO Bill Checker',               slug:'/pk/check-gepco-bill',                    category:'pakistan-utility', icon:'ReceiptText', description:'Quick GEPCO bill helper for Gujranwala region customers.',                     shortDescription:'GEPCO Bill',    isPakistani:true, tileSize:'medium', keywords:['gepco','gujranwala','bill']                          },
  { id:'fesco-bill',    name:'FESCO Bill Checker',               slug:'/pk/check-fesco-bill',                    category:'pakistan-utility', icon:'ReceiptText', description:'FESCO bill reference helper for Faisalabad electricity customers.',            shortDescription:'FESCO Bill',    isPakistani:true, tileSize:'medium', keywords:['fesco','faisalabad','bill']                          },
  { id:'hesco-bill',    name:'HESCO Bill Checker',               slug:'/pk/check-hesco-bill',                    category:'pakistan-utility', icon:'ReceiptText', description:'HESCO bill reference helper for Hyderabad and Sindh customers.',              shortDescription:'HESCO Bill',    isPakistani:true, tileSize:'medium', keywords:['hesco','hyderabad','sindh','bill']                   },
  { id:'pesco-bill',    name:'PESCO Bill Checker',               slug:'/pk/check-pesco-bill',                    category:'pakistan-utility', icon:'ReceiptText', description:'PESCO bill reference helper for Peshawar and KPK customers.',                 shortDescription:'PESCO Bill',    isPakistani:true, tileSize:'medium', keywords:['pesco','peshawar','kpk','bill']                      },
  { id:'ehsaas',        name:'Ehsaas Program Tracking',          slug:'/pk/ehsaas-program-tracking',             category:'pakistan-utility', icon:'ShieldCheck', description:'Check Ehsaas 8171 eligibility guidance and next steps.',                     shortDescription:'Ehsaas 8171',   isPakistani:true, tileSize:'small',  keywords:['ehsaas','8171','program','tracking']                 },
  { id:'bisp-payment',  name:'BISP Payment Verification',        slug:'/pk/bisp-payment-verification',           category:'pakistan-utility', icon:'BadgeCheck',  description:'Verify BISP CNIC input format and read payment guidance.',                     shortDescription:'BISP Verify',   isPakistani:true, tileSize:'small',  keywords:['bisp','payment','cnic','verify']                     },
  { id:'petrol-price',  name:'Pakistan Petrol Price Checker',    slug:'/pk/petrol-price-checker',                category:'pakistan-utility', icon:'Fuel',        description:'View current petrol and diesel price guidance for Pakistan.',                 shortDescription:'Petrol Price',  isPakistani:true, tileSize:'small',  keywords:['petrol','diesel','price','pakistan']                 },
  { id:'unit-subsidy',  name:'Electricity Unit Subsidy Calc',    slug:'/pk/electricity-unit-subsidy-calculator', category:'pakistan-utility', icon:'Calculator',  description:'Estimate subsidy eligibility ranges using electricity unit input.',           shortDescription:'Unit Subsidy',  isPakistani:true, tileSize:'small',  keywords:['electricity','unit','subsidy','calculator']          },
  { id:'ptcl-bill',     name:'PTCL Bill Checker',                slug:'/pk/ptcl-bill-checker',                   category:'pakistan-utility', icon:'Phone',       description:'PTCL bill helper for quick consumer number guidance.',                        shortDescription:'PTCL Bill',     isPakistani:true, tileSize:'small',  keywords:['ptcl','bill','telephone']                            },
  { id:'sngpl-bill',    name:'SNGPL Gas Bill Checker',           slug:'/pk/sngpl-gas-bill-checker',              category:'pakistan-utility', icon:'Flame',       description:'SNGPL gas bill helper for reference and consumer number searches.',           shortDescription:'SNGPL Gas',     isPakistani:true, tileSize:'small',  keywords:['sngpl','gas','bill']                                 },
];

export const GLOBAL_TOOLS: Tool[] = TOOLS_REGISTRY.filter(t => !t.isPakistani);
export const PK_TOOLS:     Tool[] = TOOLS_REGISTRY.filter(t =>  t.isPakistani);
